import pathlib
import subprocess

CLIs = (
    "git",
    "towncrier",
    "poetry",
    "pre-commit",
    "ruff",
    "pyenv",
)

sections = []

def get_help(cli: str) -> str:
    return subprocess.check_output(
        [cli, "--help"],
    ).decode().replace("```", "\\```")


for cli in CLIs:
    sections.append(
        f"## {cli}\n\n```\n{get_help(cli)}```\n"
    )

RESEARCH_INTRO = f"""
# Research

This document contains the `--help` output of the following CLIs:

- {'\n- '.join(map(lambda cli: cli.join("``") + ",", CLIs))[:-1] + '.'}

It was made in order to study patterns to extract information needed for designing the Cliffold scaffolding mechanism.

Generated by `scripts/generate_cliffold_research.py`.

"""

pathlib.Path("cliffold_research.md").write_text(RESEARCH_INTRO + "\n\n".join(sections))